version: '3.9'

services:
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    # Docker build the docker file in . (Run app.py)
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    # Init API after mongo is initialized
    depends_on:
      - mongodb
    volumes:
      # When files is modified in current dir it will write the file inside the container (/app)
      - .:/app